name: 'Lint Code'
description: 'Run linting checks (black, isort, flake8, mypy)'

inputs:
  working-directory:
    description: 'Working directory for commands'
    required: false
    default: '.'
  src-paths:
    description: 'Space-separated paths to lint (default: src tests)'
    required: false
    default: 'src tests'
  mypy-blocking:
    description: 'Make mypy blocking (fail build on errors)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install linting dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pip install black isort flake8 mypy
        pip install -e ".[dev]"

    - name: Run black (format check)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        black --check ${{ inputs.src-paths }}

    - name: Run isort (import sorting check)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        isort --check-only ${{ inputs.src-paths }}

    - name: Run flake8 (style check)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        flake8 ${{ inputs.src-paths }}

    - name: Run mypy (type check)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Note: Currently non-blocking by default. Set mypy-blocking=true to fail on errors.
        if [ "${{ inputs.mypy-blocking }}" = "true" ]; then
          mypy src/ --ignore-missing-imports
        else
          mypy src/ --ignore-missing-imports || true
        fi

