name: 'Build Docker Image'
description: 'Build Docker image using Buildx with caching (no push)'

inputs:
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './docker/Dockerfile'
  context-path:
    description: 'Build context path'
    required: false
    default: '.'
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: false
        load: true
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Verify image exists
      shell: bash
      run: |
        docker images | grep "${{ inputs.image-name }}" | grep "${{ inputs.image-tag }}" || exit 1
        echo "✅ Docker image built successfully: ${{ inputs.image-name }}:${{ inputs.image-tag }}"

